service: spring-boot-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  region: us-east-1
  memorySize: 512
  timeout: 15
  environment:
    SPRING_PROFILES_ACTIVE: lambda

functions:
  api:
    handler: sg.nus.iss.ceramicraft_customer_backend.LambdaHandler
    events:
      - http: ANY /{proxy+}
      - http: ANY /

plugins:
  - serverless-offline  # 本地调试可选